import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export const item = async (userId: string) => {
  await prisma.item.createMany({
    data: [
      {
        id: 1,
        itemName: '鏡月',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/kyogetsu.jpg',
        price: 3000,
        stock: 1,
        cost: 693,
        categoryId: 1,
        userId,
      },
      {
        id: 2,
        itemName: '鍛高譚(しそ)',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/tantakatan_shiso.jpg',
        price: 3000,
        stock: 1,
        cost: 1500,
        categoryId: 1,
        userId,
      },
      {
        id: 3,
        itemName: '黒霧島(芋)',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/kurokirishima.jpg',
        price: 4000,
        stock: 1,
        cost: 1500,
        categoryId: 1,
        userId,
      },
      {
        id: 4,
        itemName: 'いいちこ黒瓶(麦)',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/iichiko.jpg',
        price: 5000,
        stock: 1,
        cost: 1500,
        categoryId: 1,
        userId,
      },
      {
        id: 5,
        itemName: '吉四六(麦)',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/kichomu.jpg',
        price: 7000,
        stock: 1,
        cost: 1500,
        categoryId: 1,
        userId,
      },
      {
        id: 6,
        itemName: '鍛高譚 梅酒',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/tantakatan_umeshu.jpg',
        price: 3000,
        stock: 1,
        cost: 1500,
        categoryId: 2,
        userId,
      },
      {
        id: 7,
        itemName: 'CHOYA 梅酒',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/choya_umeshu.jpg',
        price: 5000,
        stock: 1,
        cost: 1500,
        categoryId: 2,
        userId,
      },
      {
        id: 8,
        itemName: 'I.W. ハーパーゴールドメダル',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/iw_harper_gold_medal.jpg',
        price: 6000,
        stock: 1,
        cost: 1500,
        categoryId: 3,
        userId,
      },
      {
        id: 9,
        itemName: 'ジャックダニエル',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/jack_daniels.jpg',
        price: 7000,
        stock: 1,
        cost: 1500,
        categoryId: 3,
        userId,
      },
      {
        id: 10,
        itemName: 'バランタイン 12年',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/ballantines_12years.jpg',
        price: 8000,
        stock: 1,
        cost: 1500,
        categoryId: 3,
        userId,
      },
      {
        id: 11,
        itemName: '竹鶴',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/taketsuru.jpg',
        price: 12000,
        stock: 1,
        cost: 1500,
        categoryId: 3,
        userId,
      },
      {
        id: 12,
        itemName: 'I.W.ハーパー 12年',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/iw_harper_12years.jpg',
        price: 18000,
        stock: 1,
        cost: 1500,
        categoryId: 3,
        userId,
      },
      {
        id: 13,
        itemName: 'Café de Paris',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/cafe_de_paris.jpg',
        price: 10000,
        stock: 1,
        cost: 1500,
        categoryId: 4,
        userId,
      },
      {
        id: 14,
        itemName: 'Moët & Chandon',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/moet_chandon.jpg',
        price: 22000,
        stock: 1,
        cost: 1500,
        categoryId: 4,
        userId,
      },
      {
        id: 15,
        itemName: 'Moët & Chandon Rosé',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/moet_chandon_rose.jpg',
        price: 28000,
        stock: 1,
        cost: 1500,
        categoryId: 4,
        userId,
      },
      {
        id: 16,
        itemName: 'Veuve Clicquot Yellow',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/veuve_clicquot_yellow.jpg',
        price: 30000,
        stock: 1,
        cost: 1500,
        categoryId: 4,
        userId,
      },
      {
        id: 17,
        itemName: 'Veuve Clicquot Rosé',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/veuve_clicquot_rose.jpg',
        price: 40000,
        stock: 1,
        cost: 1500,
        categoryId: 4,
        userId,
      },
      {
        id: 18,
        itemName: 'Domperignon Vintage',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/domperignon_vintage.jpg',
        price: 100000,
        stock: 1,
        cost: 1500,
        categoryId: 4,
        userId,
      },
      {
        id: 19,
        itemName: 'Domperignon Rosé',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/domperignon_rose.jpg',
        price: 180000,
        stock: 1,
        cost: 1500,
        categoryId: 4,
        userId,
      },
      {
        id: 20,
        itemName: 'エスプレッソ',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/espresso.jpg',
        price: 500,
        stock: 1,
        cost: 0,
        categoryId: 5,
        userId,
      },
      {
        id: 21,
        itemName: 'レギュラーコーヒー',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/regular_coffee.jpg',
        price: 550,
        stock: 1,
        cost: 0,
        categoryId: 5,
        userId,
      },
      {
        id: 22,
        itemName: 'カフェ・ジャポーネ',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/cafe_japones.jpg',
        price: 600,
        stock: 1,
        cost: 0,
        categoryId: 5,
        userId,
      },
      {
        id: 23,
        itemName: 'カプチーノ',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/cappuccino.jpg',
        price: 660,
        stock: 1,
        cost: 0,
        categoryId: 5,
        userId,
      },
      {
        id: 24,
        itemName: '瓶ビール',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/beer_bottle.jpg',
        price: 1000,
        stock: 1,
        cost: 200,
        categoryId: 6,
        userId,
      },
      {
        id: 25,
        itemName: 'ソフトドリンク',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/soft_drink.jpg',
        price: 500,
        stock: 1,
        cost: 0,
        categoryId: 6,
        userId,
      },
      {
        id: 26,
        itemName: 'ジュース類',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/juice.jpg',
        price: 1500,
        stock: 1,
        cost: 0,
        categoryId: 7,
        userId,
      },
      {
        id: 27,
        itemName: '値引き',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/discount.jpg',
        price: -1000,
        stock: 0,
        cost: 0,
        categoryId: 8,
        userId,
      },
      {
        id: 28,
        itemName: 'ノンアルコールビール',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/non_alcohol_beer.jpg',
        price: 800,
        stock: 1,
        cost: 130,
        categoryId: 6,
        userId,
      },
      {
        id: 29,
        itemName: 'イネディット',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/inedit.jpg',
        price: 3000,
        stock: 1,
        cost: 920,
        categoryId: 6,
        userId,
      },
      {
        id: 30,
        itemName: 'ニュートンザパズル',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/newton_the_puzzle.jpg',
        price: 32400,
        stock: 1,
        cost: 10800,
        categoryId: 9,
        userId,
      },
      {
        id: 31,
        itemName: 'カベルネソーヴィニヨン',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/Clos_Du_Val.jpg',
        price: 15600,
        stock: 1,
        cost: 5200,
        categoryId: 9,
        userId,
      },
      {
        id: 32,
        itemName: 'シャトーダルマイヤック',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/Chateau_dArmailhac.jpg',
        price: 24600,
        stock: 1,
        cost: 8200,
        categoryId: 9,
        userId,
      },
      {
        id: 33,
        itemName: 'カラレ',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/liquor-mock.jpg',
        price: 15000,
        stock: 1,
        cost: 15000,
        categoryId: 9,
        userId,
      },
      {
        id: 34,
        itemName: 'シャンベルダン',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/liquor-mock.jpg',
        price: 30000,
        stock: 1,
        cost: 30000,
        categoryId: 9,
        userId,
      },
      {
        id: 35,
        itemName: 'sdsadf',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/12f4e60d-6664-4ff2-8e60-ab6a03220ca7/1650260052758.png',
        price: 3000,
        stock: 3,
        cost: 500,
        categoryId: 1,
        userId: '12f4e60d-6664-4ff2-8e60-ab6a03220ca7',
      },
      {
        id: 36,
        itemName: 'たま',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/53a3ccf3-430f-47e6-b1dd-a2d8a209587b/1650260275167.jpeg',
        price: 3000,
        stock: 4,
        cost: 500,
        categoryId: 9,
        userId,
      },
      {
        id: 37,
        itemName: '延長',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/53a3ccf3-430f-47e6-b1dd-a2d8a209587b/1650276166010.jpeg',
        price: 1000,
        stock: 100,
        cost: 0,
        categoryId: 8,
        userId,
      },
      {
        id: 38,
        itemName: 'ビール',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/12f4e60d-6664-4ff2-8e60-ab6a03220ca7/1650348256035.jpeg',
        price: 1000,
        stock: 3,
        cost: 200,
        categoryId: 6,
        userId: '12f4e60d-6664-4ff2-8e60-ab6a03220ca7',
      },
      {
        id: 40,
        itemName: 'いいちこ',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/12f4e60d-6664-4ff2-8e60-ab6a03220ca7/1650348368765.jpeg',
        price: 13000,
        stock: 3,
        cost: 500,
        categoryId: 1,
        userId: '12f4e60d-6664-4ff2-8e60-ab6a03220ca7',
      },
      {
        id: 41,
        itemName: 'シャンパン',
        itemUrl:
          'https://storage.googleapis.com/lapin-pos-storage/item/12f4e60d-6664-4ff2-8e60-ab6a03220ca7/1650348410591.jpeg',
        price: 23000,
        stock: 3,
        cost: 500,
        categoryId: 4,
        userId: '12f4e60d-6664-4ff2-8e60-ab6a03220ca7',
      },
    ],
  });
};
