import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export const sales = async (userId: string) => {
  await prisma.sale.createMany({
    data: [
      {
        id: 6,
        customerName: 'NOBOりん',
        customerKana: 'ノボリン',
        receipt: '',
        castName: 'りか',
        planName: 'ボトルキープ フリータイム(4時間制)',
        planPrice: 13000,
        enteredAt: new Date(),
        exitedAt: new Date(),
        totalTime: 4,
        extendedTime: 0,
        extendedPrice: 0,
        subtotal: 29000,
        servicePrice: 2900,
        taxPrice: 2900,
        totalPrice: 34800,
        isCreditCard: true,
        sessionId: 1,
        userId,
      },
      {
        id: 7,
        customerName: 'グリマネ',
        customerKana: 'グリマネ',
        receipt: '',
        castName: 'りか',
        planName: '単品プラン',
        planPrice: 4000,
        enteredAt: new Date(),
        exitedAt: new Date(),
        totalTime: 65,
        extendedTime: 5,
        extendedPrice: 1000,
        subtotal: 11000,
        servicePrice: 1100,
        taxPrice: 1100,
        totalPrice: 13200,
        isCreditCard: true,
        sessionId: 1,
        userId,
      },
      {
        id: 8,
        customerName: 'ぷらっち',
        customerKana: 'プラッチ',
        receipt: '',
        castName: 'りか',
        planName: 'ボトルキープ フリータイム(4時間制)',
        planPrice: 13000,
        enteredAt: new Date(),
        exitedAt: new Date(),
        totalTime: 98,
        extendedTime: 0,
        extendedPrice: 0,
        subtotal: 35000,
        servicePrice: 3500,
        taxPrice: 3500,
        totalPrice: 42000,
        isCreditCard: true,
        sessionId: 1,
        userId,
      },
      {
        id: 9,
        customerName: 'なみなみ',
        customerKana: 'ナミナミ',
        receipt: '',
        castName: 'りか',
        planName: 'ボトルキープ フリータイム(4時間制)',
        planPrice: 13000,
        enteredAt: new Date(),
        exitedAt: new Date(),
        totalTime: 79,
        extendedTime: 0,
        extendedPrice: 0,
        subtotal: 18000,
        servicePrice: 1800,
        taxPrice: 1800,
        totalPrice: 21600,
        isCreditCard: true,
        sessionId: 1,
        userId,
      },
      {
        id: 10,
        customerName: 'ケーーーーン',
        customerKana: 'ケーーーーン',
        receipt: '',
        castName: 'りか',
        planName: 'ボトルキープ フリータイム(4時間制)',
        planPrice: 13000,
        enteredAt: new Date(),
        exitedAt: new Date(),
        totalTime: 3,
        extendedTime: 0,
        extendedPrice: 0,
        subtotal: 22000,
        servicePrice: 2200,
        taxPrice: 2200,
        totalPrice: 26400,
        isCreditCard: false,
        sessionId: 1,
        userId,
      },
    ],
  });
};
